[project]
authors = ["Mahesh Binzer-Panchal <mahesh.binzer-panchal@nbis.se>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "nextflow-quarto-multiqc-demo"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
nextflow = {cmd = "nextflow run $SCRIPT -resume", env = { SCRIPT = "main.nf" }}

[dependencies]
quarto = ">=1.5.55,<2"
nextflow = ">=24.4.4,<25"
jupyter = ">=1.1.1,<2"
multiqc = ">=1.24.1,<2"
papermill = ">=2.6.0,<3"
